### PR TITLE
Moving the scripts for benchmark to awslabs managed github repository

### PR DESCRIPTION
**Pull request by leleamol**

### CODE REVIEW

**Comment by lupesko** [comment]
Great to see this :)

**Comment by lanking520** [comment]
+1

**Comment by lebeg** [comment]
Maybe we could improve and refactor those scripts at some point. For example make them run on python 3.

**Comment by vishaalkapoor** [comment]
@leleamol - I wanted to check in on this PR as it would be great to see these go on given that many folks are already using forked versions of this repo to run their tests. 

I think there was just one specific ask by @lupesko to include copyright headers. Once those are done, this LGTM from the perspective of consolidating the source into a central repo. 

If there are refactoring concerns, I propose they are captured in an issue so that they can be passed on in ownership (@leleamol isn't working on this anymore afaik).

Thanks!

**Pull request closed without merging**
